### PR TITLE
Apidocs perdiem 10172019

### PR DESCRIPTION
**Pull request by DaleFreyCTAC**
Adding in the OpenAPI-Specification-File for the GSA.gov content-API and Perdim-API in order to conform with the required standards

### CODE REVIEW

**Comment by Ryandaydev** [comment]
Here are recommendations for this prior to merging. You can see these implemented in the sample API docs here in the "_apidocs/sample-api.md" file in the repo and explained in the instructions in the "apidocs.md" file.

* Add a section heading for "OpenAPI Specification File"
* Use "OpenAPI" instead of "Swagger" format.
* Rename the files to openapi.yml
* Store the file under the api name subfolder
* Put version 2 in the OpenAPI files
* Add API key to the OpenAPI spec

**Comment by DaleFreyCTAC** [comment]
@Ryandaydev - I believe I have applied all recommendations to this branch correctly - please review and let me know if there are any other changes I should apply.

Thanks!
- Dale

**Comment by DaleFreyCTAC** [comment]
@Ryandaydev - Oops, there was a duplicate link pointing to the old path - this is now resolved

**Comment by Ryandaydev** [comment]
@DaleFrey I validated the OpenAPI files and a few updates were needed that I made directly. I tested them with Postman successfully. Please take a look and make sure my changes are OK.

**Comment by DaleFreyCTAC** [comment]
@Ryandaydev - Oh! Wow, sorry for the mistakes, I see what you did and I understand why. Thanks for the updates!

They look good to me,
- Dale

**Comment by Ryandaydev** [comment]
@DaleFrey ah, sorry I see a couple more items now:
- Content API in the HTTP response section says JSON will be returned, but I believe this is an XML API.
- Both APIs: misspelling of the word "parameters" in the HTTP response section.
- Content API has extra OpenAPI Specification at the bottom.

**Comment by DaleFreyCTAC** [comment]
@Ryandaydev - Oops, I apologize for all the mistakes. Thank you very much for catching them. I have updated this branch with these fixes

**Comment by Ryandaydev** [comment]
@DaleFrey looks like all the test passed. Are you ready for me to merge into prod?

**Comment by DaleFreyCTAC** [comment]
@Ryandaydev - Thanks Ryan! Yes, I am ready whenever you are

**Pull request merged**
