### PR TITLE
adding the api.data.gov docs

### PR DESCRIPTION
**Pull request by gbinal**
cc @Ryandaydev and @jfredrickson5

### CODE REVIEW

**Comment by Ryandaydev** [comment]
@gbinal this is getting a build error because this line of code is trying to use an email an HREF:

```Reach out to the api.data.gov team at [api.data.gov@gsa.gov](api.data.gov@gsa.gov). ```


I'm not sure the syntax for a mailto: in markdown, but that would probably fix it.

**Comment by gbinal** [comment]
ah!  good catch.  Should be fixed now.

**Comment by gbinal** [comment]
Hey gents - any thoughts on merging away?

**Comment by KehindeOgundolie** [comment]
@gbinal Merge complete.

**Pull request merged**
