### PR TITLE
Apidocs codegov 08122019

### PR DESCRIPTION
**Pull request by seanstar12**
@Ryandaydev @gbinal 
I attempted to update the openapi.yaml file to use the `x-api-key` header, but every attempt failed due to CORs. I attempted to mitigate this by adding a forced header to api.data.gov, with no luck. I updated the documentation to push users more towards the header implementation.

### CODE REVIEW

**Comment by seanstar12** [comment]
@Ryandaydev I updated the readme text. I also attempted to add in header authentication via the openapi.yaml file, but there seems to be a bug/limitation with the document viewer that prevents adding the header on requests. So, I reverted the yaml doc to use the url parameter, but still have the the readme suggesting to use the header authentication.

**Comment by Ryandaydev** [comment]
@seanstar12 take a look at this example: https://open.gsa.gov/api/sample-api/#api-calls

**Comment by seanstar12** [comment]
@Ryandaydev Found the mistake, it was in the api config. I had the response header set for CORS instead of the request header. Should be good now.

**Comment by gbinal** [comment]
@Ryandaydev and @jfredrickson5 - I've paired with @seanstar12 and this looks good to me.  

The only test that's not passing appears to be because of a gemfile.lock file that's unrelated to this PR.  The code.gov team is hoping to ship an update on their site today that's dependent on this going live, so if you see this and are game to merge today, that'd be awesome but if you don't, I may go ahead and do it at COB.

**Comment by Ryandaydev** [comment]
@seanstar12 this is merged to prod.

**Pull request merged**
