### PR TITLE
sam contract api changes

### PR DESCRIPTION
**Pull request by RamyaKalagara**
sam contract api changes

### CODE REVIEW

**Comment by jfredrickson5** [comment]
@RamyaKalagara We just moved the automated tests from CircleCI to GitHub Actions, which is why the tests currently show as failing. Please click "Update branch" in this PR at your convenience to kick off the new tests.

**Comment by gbinal** [comment]
This looks good to me.

**Comment by gbinal** [comment]
Ah, sorry.  I missed the earlier note that gets to why the tests are failing.  It would be good to redress that before we merge.

**Comment by gbinal** [comment]
Tests are all passing now.  Let's merge!

**Pull request merged**
